version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
