name: Check Pull Request

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'poetry.lock'

jobs:
  pytest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: local
          POSTGRES_USER: local
          POSTGRES_PASSWORD: local
        options: >-
          --health-cmd="pg_isready -U test_user -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5



    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run Redis cluster
        uses: vishnudxb/redis-cluster@1.0.5
        with:
          master1-port: 30001
          master2-port: 30002
          master3-port: 30003
          slave1-port: 30004
          slave2-port: 30005
          slave3-port: 30006

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        env:
          DATABASE_URL: postgresql://local:local@localhost:5432/local
          REDIS_URL: redis://localhost:6379
        run: |
          poetry run pytest tests/
